// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC23vsb6vPmqDBfMxI_vHNxsslEpqD8iLw',
    appId: '1:290316540249:web:6c55131b0ab477da315448',
    messagingSenderId: '290316540249',
    projectId: 'theas-demo',
    authDomain: 'theas-demo.firebaseapp.com',
    databaseURL: 'https://theas-demo-default-rtdb.firebaseio.com',
    storageBucket: 'theas-demo.appspot.com',
    measurementId: 'G-N719T71XQT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAT1VRlWIL_FQ1g79TwmY0lWpS7jFCDLSs',
    appId: '1:290316540249:android:6c9408bd80e3652a315448',
    messagingSenderId: '290316540249',
    projectId: 'theas-demo',
    databaseURL: 'https://theas-demo-default-rtdb.firebaseio.com',
    storageBucket: 'theas-demo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJqoeeq5zpj2XT1TDiJJmPtolbqP7oikA',
    appId: '1:290316540249:ios:d222055212412c73315448',
    messagingSenderId: '290316540249',
    projectId: 'theas-demo',
    databaseURL: 'https://theas-demo-default-rtdb.firebaseio.com',
    storageBucket: 'theas-demo.appspot.com',
    iosClientId: '290316540249-98g5l56ejq53dkdngd6ap5rempbikb47.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJqoeeq5zpj2XT1TDiJJmPtolbqP7oikA',
    appId: '1:290316540249:ios:d222055212412c73315448',
    messagingSenderId: '290316540249',
    projectId: 'theas-demo',
    databaseURL: 'https://theas-demo-default-rtdb.firebaseio.com',
    storageBucket: 'theas-demo.appspot.com',
    iosClientId: '290316540249-98g5l56ejq53dkdngd6ap5rempbikb47.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
